In [1]:
import numpy as np
import math

In [2]:
p = [[4,2],[5,2],[6,2],[3,3],[7,3],[2,4],[8,4],[2,5],[6,5],[4,6],[2,7]]

In [39]:
theta = []

for i in range(11):
    for j in range(i+1,11):
        if (p[i][0]-p[j][0] != 0):
            s = np.round((p[i][1]-p[j][1]) / (p[i][0]-p[j][0]),2)
            print(i,',',j,':',s)
            mc = np.round(math.atan(s),3)
            mcd = np.round(np.degrees(mc),0)
            if mcd not in theta:
                print(i,',',j,':',mcd)
                theta.append(mcd)
        else:
            mcd = 90.0
            if mcd not in theta:
                print(i,',',j,':',mcd)
                theta.append(mcd)

0 , 1 : -0.0
0 , 1 : -0.0
0 , 2 : -0.0
0 , 3 : -1.0
0 , 3 : -45.0
0 , 4 : 0.33
0 , 4 : 18.0
0 , 5 : -1.0
0 , 6 : 0.5
0 , 6 : 27.0
0 , 7 : -1.5
0 , 7 : -56.0
0 , 8 : 1.5
0 , 8 : 56.0
0 , 9 : 90.0
0 , 10 : -2.5
0 , 10 : -68.0
1 , 2 : -0.0
1 , 3 : -0.5
1 , 3 : -27.0
1 , 4 : 0.5
1 , 5 : -0.67
1 , 5 : -34.0
1 , 6 : 0.67
1 , 6 : 34.0
1 , 7 : -1.0
1 , 8 : 3.0
1 , 8 : 72.0
1 , 9 : -4.0
1 , 9 : -76.0
1 , 10 : -1.67
1 , 10 : -59.0
2 , 3 : -0.33
2 , 3 : -18.0
2 , 4 : 1.0
2 , 4 : 45.0
2 , 5 : -0.5
2 , 6 : 1.0
2 , 7 : -0.75
2 , 7 : -37.0
2 , 9 : -2.0
2 , 9 : -63.0
2 , 10 : -1.25
2 , 10 : -51.0
3 , 4 : -0.0
3 , 5 : -1.0
3 , 6 : 0.2
3 , 6 : 11.0
3 , 7 : -2.0
3 , 8 : 0.67
3 , 9 : 3.0
3 , 10 : -4.0
4 , 5 : -0.2
4 , 5 : -11.0
4 , 6 : 1.0
4 , 7 : -0.4
4 , 7 : -22.0
4 , 8 : -2.0
4 , 9 : -1.0
4 , 10 : -0.8
4 , 10 : -39.0
5 , 6 : -0.0
5 , 8 : 0.25
5 , 8 : 14.0
5 , 9 : 1.0
6 , 7 : -0.17
6 , 7 : -10.0
6 , 8 : -0.5
6 , 9 : -0.5
6 , 10 : -0.5
7 , 8 : -0.0
7 , 9 : 0.5
8 , 9 : -0.5
8 , 10 : -0.5
9 , 10 : -0.5


In [40]:
theta

[-0.0,
 -45.0,
 18.0,
 27.0,
 -56.0,
 56.0,
 90.0,
 -68.0,
 -27.0,
 -34.0,
 34.0,
 72.0,
 -76.0,
 -59.0,
 -18.0,
 45.0,
 -37.0,
 -63.0,
 -51.0,
 11.0,
 -11.0,
 -22.0,
 -39.0,
 14.0,
 -10.0]

In [41]:
theta.sort()
theta

[-76.0,
 -68.0,
 -63.0,
 -59.0,
 -56.0,
 -51.0,
 -45.0,
 -39.0,
 -37.0,
 -34.0,
 -27.0,
 -22.0,
 -18.0,
 -11.0,
 -10.0,
 -0.0,
 11.0,
 14.0,
 18.0,
 27.0,
 34.0,
 45.0,
 56.0,
 72.0,
 90.0]

In [42]:
len(theta)

25

In [95]:
trs = []
for i in range(len(theta)):
    rho = []
    for j in range(11):
        temp = p[j][0]*math.cos(np.deg2rad(theta[i]))+p[j][1]*math.sin(np.deg2rad(theta[i]))
        rho.append(np.round(temp,2))
    rho.sort(reverse=True)
    trs.append(rho)

In [96]:
trs

[[-0.49, -0.73, -0.97, -1.22, -1.95, -2.19, -3.4, -3.4, -4.37, -4.85, -6.31],
 [0.39, 0.02, -0.16, -0.36, -0.71, -1.66, -2.39, -2.96, -3.89, -4.06, -5.74],
 [0.94, 0.5, 0.49, 0.07, 0.03, -1.31, -1.73, -2.66, -3.53, -3.55, -5.33],
 [1.38, 1.03, 0.86, 0.69, 0.35, -1.03, -1.2, -2.4, -3.08, -3.26, -4.97],
 [1.7, 1.43, 1.16, 1.14, 0.58, -0.79, -0.81, -2.2, -2.74, -3.03, -4.68],
 [2.22, 2.07, 1.93, 1.59, 0.96, -0.11, -0.44, -1.85, -2.15, -2.63, -4.18],
 [2.83, 2.83, 2.83, 2.12, 1.41, 0.71, 0.0, -1.41, -1.41, -2.12, -3.54],
 [3.7, 3.55, 3.4, 2.63, 1.85, 1.52, 0.44, -0.67, -0.96, -1.59, -2.85],
 [3.98, 3.79, 3.59, 2.79, 1.99, 1.78, 0.59, -0.42, -0.81, -1.41, -2.62],
 [4.4, 4.13, 3.86, 3.03, 2.2, 2.18, 0.81, -0.04, -0.58, -1.14, -2.26],
 [5.31, 4.88, 4.44, 3.55, 3.08, 2.66, 1.31, 0.84, -0.03, -0.49, -1.4],
 [5.92, 5.37, 4.81, 3.89, 3.69, 2.96, 1.66, 1.46, 0.36, -0.02, -0.77],
 [6.37, 5.73, 5.09, 4.16, 4.14, 3.19, 1.95, 1.93, 0.67, 0.36, -0.26],
 [7.09, 6.3, 5.51, 4.94, 4.53, 3.54, 2.78, 2.37, 1

In [97]:
rhou = np.unique(trs)

In [98]:
rhou

array([-6.31, -5.74, -5.33, -4.97, -4.85, -4.68, -4.37, -4.18, -4.06,
       -3.89, -3.55, -3.54, -3.53, -3.4 , -3.26, -3.08, -3.03, -2.96,
       -2.85, -2.74, -2.66, -2.63, -2.62, -2.4 , -2.39, -2.26, -2.2 ,
       -2.19, -2.15, -2.12, -1.95, -1.85, -1.73, -1.66, -1.59, -1.41,
       -1.4 , -1.31, -1.22, -1.2 , -1.14, -1.03, -0.97, -0.96, -0.81,
       -0.79, -0.77, -0.73, -0.71, -0.67, -0.58, -0.49, -0.44, -0.42,
       -0.36, -0.26, -0.16, -0.11, -0.04, -0.03, -0.02,  0.  ,  0.02,
        0.03,  0.07,  0.35,  0.36,  0.39,  0.44,  0.49,  0.5 ,  0.58,
        0.59,  0.63,  0.67,  0.69,  0.71,  0.75,  0.81,  0.84,  0.86,
        0.94,  0.96,  1.01,  1.03,  1.1 ,  1.14,  1.16,  1.2 ,  1.28,
        1.31,  1.38,  1.41,  1.43,  1.46,  1.52,  1.59,  1.66,  1.7 ,
        1.78,  1.85,  1.93,  1.95,  1.99,  2.  ,  2.07,  2.12,  2.18,
        2.2 ,  2.22,  2.37,  2.43,  2.63,  2.66,  2.73,  2.78,  2.79,
        2.83,  2.9 ,  2.91,  2.92,  2.96,  3.  ,  3.03,  3.08,  3.14,
        3.15,  3.19,

In [99]:
f1 = []
f23 = []
tf = []
rf = []
for k in rhou:
    for i in range(len(theta)):
        count = 0
        for j in range(len(p)):
            if trs[i][j] == k:
                count += 1
        f1.append([theta[i],k,count])
        if count > 1:
            f23.append([theta[i],k,count])     
            tf.append(theta[i])
            rf.append(k)

In [100]:
f23

[[-76.0, -3.4, 2],
 [-45.0, -1.41, 2],
 [-0.0, 2.0, 3],
 [90.0, 2.0, 3],
 [-45.0, 2.83, 3],
 [90.0, 3.0, 2],
 [-0.0, 4.0, 2],
 [90.0, 4.0, 2],
 [45.0, 4.24, 3],
 [45.0, 4.95, 2],
 [90.0, 5.0, 2],
 [-0.0, 6.0, 2],
 [45.0, 7.07, 2]]

In [101]:
tf.sort()

In [102]:
ftf = np.unique(tf)

In [103]:
ftf

array([-76., -45.,  -0.,  45.,  90.])

In [104]:
rf.sort()

In [105]:
frf = np.unique(rf)

In [106]:
frf

array([-3.4 , -1.41,  2.  ,  2.83,  3.  ,  4.  ,  4.24,  4.95,  5.  ,
        6.  ,  7.07])